# Dockerfile_frontend

# Use node version 14 as the base image
FROM node:14

# Set the working directory inside the container to '/app'
WORKDIR /app

# Install app dependencies
# Use a wildcard (*) to copy both package.json and package-lock.json 
COPY package*.json ./

# Install the Node.js dependencies from the package.json file
RUN npm install

# Copy the rest of the application source code into the container
COPY . .

# Build the application using the specified scripts in package.json
RUN npm run build

# Expose port 3000 for the application
EXPOSE 3000

# Start the application using npm start command
CMD [ "npm", "start" ]
